DetailsViewController transferred to CollectionView
urutet/MovieSaver pull request #11
Opened 2022-04-05 12:10 UTC by urutet

2022-04-09 00:29 UTC, wadimbylvar requested changes

2022-04-09 00:29 UTC, wadimbylvar commented on MovieSaver/CustomUIElements/ImageCollectionViewCell.swift
> +    addSubview(imageView)
`contentView.addSubview`

2022-04-09 00:29 UTC, wadimbylvar commented on MovieSaver/CustomUIElements/LabelCollectionViewCell.swift
> +    addSubview(label)
То же самое

2022-04-09 00:29 UTC, wadimbylvar commented on MovieSaver/CustomUIElements/TextViewCollectionViewCell.swift
> +    addSubview(textView)
То же самое

2022-04-09 00:29 UTC, wadimbylvar commented on MovieSaver/CustomUIElements/WebViewCollectionViewCell.swift
> +    addSubview(webView)
То же самое

2022-04-10 18:41 UTC, urutet commented on MovieSaver/CustomUIElements/ImageCollectionViewCell.swift
> +    addSubview(imageView)
Done

2022-04-10 18:41 UTC, urutet commented on MovieSaver/CustomUIElements/LabelCollectionViewCell.swift
> +    addSubview(label)
Done

2022-04-10 18:41 UTC, urutet commented on MovieSaver/CustomUIElements/TextViewCollectionViewCell.swift
> +    addSubview(textView)
Done

2022-04-10 18:41 UTC, urutet commented on MovieSaver/CustomUIElements/WebViewCollectionViewCell.swift
> +    addSubview(webView)
Done

2022-04-11 06:01 UTC, wadimbylvar commented on MovieSaver/Controller/MovieDetailViewController.swift
> +  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
This method is too long

2022-04-13 15:59 UTC, wadimbylvar requested changes

2022-04-13 15:59 UTC, wadimbylvar commented on MovieSaver/Controller/MovieDetailViewController.swift
> +  private var movie = Movie(
I mentioned this moment on our call

2022-04-13 20:04 UTC, urutet commented on MovieSaver/Controller/MovieDetailViewController.swift
> +  private var movie = Movie(
The problem was resolved in branch feature/addMovieViewController-to-mvvm

2022-04-14 14:54 UTC, urutet commented on MovieSaver/Controller/MovieDetailViewController.swift
> +  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
Divided into parts in the latest commit

2022-04-14 18:22 UTC, wadimbylvar approved these changes

2022-04-14 20:27 UTC, merged