Feature/merging change name view controller
urutet/MovieSaver pull request #3
Opened 2022-03-21 11:07 UTC by urutet

All ViewControllers merged to one base ViewController

2022-03-21 11:53 UTC, wadimbylvar requested changes

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +  private func showChangeInfoViewController
Сигнатура метода поместится в 1 строку

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +    let viewController: BaseChangeInfoViewController = {
Здесь не нужно замыкание

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +      viewController.outputHandler = {
BaseChangeInfoViewController не должен сильно удерживать AddMovieViewController (self). В данном случае утечки памяти не будет только за счет того, что AddMovieViewController не удерживает BaseChangeInfoViewController. Нужно добавить либо weak, либо unowned self

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +    if let url = URL(string: youTubeLinkStackView.getValue()) {
guard let вместо if let, чтобы уменьшить уровень вложенности (golden path)

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +        releaseDate: dateFormatter
перенос строки не нужен

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +      self,
У тебя тут должна быть ошибка компиляции. Ты не можешь использовать self в дефолтном значении проперти

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +  private let ratingArray = Array(stride(from: 0.0, to: 10.0, by: 0.1))
В константы

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +    default:
А зачем тут default? Ты же обработал все кейсы

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +    default:
То же самое

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +    if let name = infoTextField.text {
Guard

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +        if name.isEmpty {
Guard

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +            present(alert, animated: true, completion: nil)
Отступ

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +            navigationController?.popViewController(animated: true)
Отступ

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +            navigationController?.popViewController(animated: true)
И лучше, чтобы pop делал вызывающий вью контроллер в outputHandler

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +    navigationController?.popViewController(animated: true)
То же самое

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +    if let link = infoTextField.text {
Guard

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +      return 1
Используй shorthand return (т.е слово return не нужно)
И во всех случаях далее

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +          return String(format: "%.1f", ratingArray[row])
Отступ

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/MovieListViewController.swift
> +      viewController.eventHandler = { movie in
Потенциальная утечка памяти

2022-03-21 11:53 UTC, wadimbylvar commented on MovieSaver/Controller/MovieListViewController.swift
> +        self.moviesList = movies
Ты мог просто сделать `self.moviesList.append(movie)`, вместо 3х строк

2022-03-23 09:08 UTC, wadimbylvar commented on MovieSaver/Controller/AddMovieViewController.swift
> +      switch $0 {
По-хорошему, если ты используешь self несколько раз в замыкании, то стоит ее сильно захватить
`guard let strongSelf = self else { return }`
и работать дальше со `strongSelf`

2022-03-23 09:08 UTC, wadimbylvar commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +      !name.isEmpty else {
`else {` на новой строке
но в целом у тебя бы все выражение guard влезло бы в 1 строку

2022-03-24 16:25 UTC, urutet commented on MovieSaver/Controller/AddMovieViewController.swift
> +      switch $0 {
Done

2022-03-24 16:25 UTC, urutet commented on MovieSaver/Controller/BaseChangeInfoViewController.swift
> +      !name.isEmpty else {
Done

2022-03-29 14:22 UTC, wadimbylvar approved these changes

2022-03-29 14:26 UTC, merged